#!/bin/bash

TOP_DIR="$(cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"

cd ${TOP_DIR}
echo 'Creating the ROS workspace'
if [ ! -d "${TOP_DIR}/src" ]; then
  wstool init src
fi
wstool merge -t src blam.rosinstall
wstool up -t src
catkin_make --cmake-args -DCMAKE_BUILD_TYPE=Release
source ${TOP_DIR}/devel/setup.bash
